In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms
print (torch.__version__)

2.8.0


1. Introduction to Tensors

**torch.tensor ()** là hàm tạo một Tensor mới - kiểu dữ liệu trung tâm của PyTorch

- torch.tensor (data), data có thể là:

    + list Python

    + numpy array

    + giá trị đơn (scalar)

- params:
    + dtype : data type (torch.float32, torch.int64,...)

    + device : storage location ('cpu' or 'cuda')

    + requires_grad : if True, PyTorch will follow tensor to automatically compute gradient
    

a. Create Tensors

In [2]:
scalar = torch.tensor (7)
lst = torch.tensor ([1,2,3])
arr = torch.tensor (np.array ([2,3,4]))
print (lst)
print (scalar)
print (arr)

print ("ndim")
print (scalar.ndim)
print (lst.ndim)
print (arr.ndim)

# Get tensor back as Python int
print (scalar.item ())
print (lst.shape)

tensor([1, 2, 3])
tensor(7)
tensor([2, 3, 4])
ndim
0
1
1
7
torch.Size([3])


In [3]:
matrix = torch.tensor ([
    [7, 8],
    [9, 10]
])
print (matrix.shape)
matrix [1]

torch.Size([2, 2])


tensor([ 9, 10])

b. Random tensors

In [4]:
random_tensor = torch.rand (3, 4)
random_tensor

tensor([[0.8634, 0.2413, 0.1079, 0.0710],
        [0.4111, 0.5711, 0.9505, 0.5811],
        [0.8228, 0.2426, 0.7666, 0.0572]])

In [5]:
# height, width, colour channels (R, G, B)
random_image_size_tensor = torch.rand (size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

**c. Zeros and ones**

In [6]:
zeros = torch.zeros (size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
ones = torch.ones (size=(4,3))
print (ones.dtype)
ones

torch.float32


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

**d. Create a range of tensors and tensors-like**

In [8]:
# Use torch.arange () and get deprecated message
one_to_ten = torch.arange (start=1, end=11, step=1)
print (one_to_ten)

# Create tensors-like
ten_zeros = torch.zeros_like (input=one_to_ten)
ten_zeros

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**e. Tensor Datatypes**

**Note**: Tensor datatypes is one of the 3 big error u'll run into with PyTorch and Deep Learning

1. Tensors not right datatype

2. Tensors not right shape

3. Tensors not on the right device

**Torch Datatype**

+ torch.float32 / torch.float

+ torch.float64 / torch.double

+ torch.float16 / torch.half

+ torch.int8

+ torch.int16 / torch.short

+ torch.int32 / torch.int

+ torch.int64 / torch.long

+ torch.bool

In [9]:
float_32_tensor = torch.tensor (
    [3.0, 6.0, 9.0],
    dtype=None,   # what datatype is the tensor (e.g. float32 or float16)
    device=None,  # what devices is your tensor on
    requires_grad=False # whether or not to track gradients with this tensors operations
)
print (float_32_tensor)
print (float_32_tensor.dtype)

float_16_tensor = float_32_tensor.type (torch.float16)
print (float_16_tensor)

print (float_16_tensor * float_32_tensor)

int_32_tensor = torch.tensor (
    [3,6,7],
    dtype=torch.long,
)
print (int_32_tensor)

tensor([3., 6., 9.])
torch.float32
tensor([3., 6., 9.], dtype=torch.float16)
tensor([ 9., 36., 81.])
tensor([3, 6, 7])


**f. Getting Information from tensors (tensor attributes)**

In [10]:
some_tensor = torch.rand (size=(3,4))
print (some_tensor)

print (f"Datatype of tensor: {some_tensor.dtype}")
print (f"Shape of tensor: {some_tensor.shape}")
print (f"Device tensor is on: {some_tensor.device}")
print (f"Tensor is required to compute gradient: {some_tensor.requires_grad}")
print (f"Gradient of tensor is: {some_tensor.grad}")
print (f"NDim of tensor: {some_tensor.ndim} (.ndim or .dim () )")
print (f"Number of elements in tensor: {some_tensor.numel ()}")
print (f"Tensor is on GPU: {some_tensor.is_cuda}")
print (f"Transform tensor: {some_tensor.T}")

tensor([[0.1378, 0.2000, 0.3211, 0.2318],
        [0.4215, 0.8274, 0.7110, 0.0093],
        [0.1663, 0.5993, 0.4018, 0.4078]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
Tensor is required to compute gradient: False
Gradient of tensor is: None
NDim of tensor: 2 (.ndim or .dim () )
Number of elements in tensor: 12
Tensor is on GPU: False
Transform tensor: tensor([[0.1378, 0.4215, 0.1663],
        [0.2000, 0.8274, 0.5993],
        [0.3211, 0.7110, 0.4018],
        [0.2318, 0.0093, 0.4078]])


**g. Tensors Operations**

Tensor operations include:

+ Addition

+ Subtraction

+ Multiplication (element-wise)

+ Division

+ Matrix multiplication

In [11]:
# Create a tensor and add 10 to it
x = torch.tensor ([1,2,3], dtype=torch.int32)
y = torch.tensor ([4,5,6], dtype=torch.float32)

print (f"x + 10 = {x+10}")
print (f"x - 10 = {x-10}")
print (f"x * 10 = {x*10}")
print (f"x / 10 = {x/10}")

print (f"x + y = {x+y}")
print (f"x - y = {x-y}")
print (f"x * y = {x*y}")
print (f"x / y = {x/y}")
print ("Relatively")
print (f"x + y = {torch.add (x, y)}")
print (f"x - y = {torch.sub (x, y)}")
print (f"x * y = {torch.mul (x, y)}")
print (f"x / y = {torch.div (x, y)}")

x + 10 = tensor([11, 12, 13], dtype=torch.int32)
x - 10 = tensor([-9, -8, -7], dtype=torch.int32)
x * 10 = tensor([10, 20, 30], dtype=torch.int32)
x / 10 = tensor([0.1000, 0.2000, 0.3000])
x + y = tensor([5., 7., 9.])
x - y = tensor([-3., -3., -3.])
x * y = tensor([ 4., 10., 18.])
x / y = tensor([0.2500, 0.4000, 0.5000])
Relatively
x + y = tensor([5., 7., 9.])
x - y = tensor([-3., -3., -3.])
x * y = tensor([ 4., 10., 18.])
x / y = tensor([0.2500, 0.4000, 0.5000])


**h. Matrix Operations**

In [17]:
print (f"x @ y = {torch.matmul (x, y.T.to(torch.int32))}")
print (f"x @ y = {x @ y.T.to(torch.int32)}")

x @ y = 32
x @ y = 32


**i. Tensor Aggregation**

In [36]:
x = torch.arange (1, 100, 10)
y = torch.tensor ([[1,2,3],
                   [4,5,6]])
print (f"Max is {torch.max (x)} (torch.max () or x.max ())")
print (f"Min is {x.min ()}")
print (f"Sum is {torch.sum (x)}")
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
print (f"Mean is {torch.mean (x.type (torch.float32))}")
print (f"Median is {x.type (torch.float32).mean ()}")
print (f"Std is {torch.std (x.type (torch.float32))}")
print (f"Variance is {torch.var (x.type (torch.float32))}")

print (f"Sum of columns is {torch.sum (y, dim=0)}") 
print (f"Sum of rows is {torch.sum (y, dim=1)}")

print (f"Argmax is {torch.argmax (x)}")
print (f"Argmin is {x.argmin ()}")

print (f"Prod is {torch.prod (x)}") # Tich tat ca phan tu
print (f"Cumsum is {torch.cumsum (y, dim=0)}") # Tong tich luy
print (f"Cumprod is {torch.cumprod (y, dim=1)}")
print (f"If elements != 0: {torch.all (x)}")
print (f"If at least 1 element != 0 : {torch.any (x)}")

Max is 91 (torch.max () or x.max ())
Min is 1
Sum is 460
Mean is 46.0
Median is 46.0
Std is 30.27650260925293
Variance is 916.6666870117188
Sum of columns is tensor([5, 7, 9])
Sum of rows is tensor([ 6, 15])
Argmax is 9
Argmin is 0
Prod is 478015854767451
Cumsum is tensor([[1, 2, 3],
        [5, 7, 9]])
Cumprod is tensor([[  1,   2,   6],
        [  4,  20, 120]])
If elements != 0: True
If at least 1 element != 0 : True


**j. Reshaping, stacking, squeezing, and unsqueezing tensors**

+ Reshaping: reshapes an input tensor to a defined shape

+ View: Return a view of an input tensor of certain shape but keep the same memory as the original tensor

+ Stacking: Combine multiple tensors on top of each other (vstack) or side by side (hstack)

+ Squeeze: Removes all 1 dimensions from a tensore

+ Unsqueeze : Add a 1 dimension to a target tensor

+ Permute : Return a view of the input with dimensions permuted (swapped) in a certain way

In [52]:
x = torch.arange (1., 10.)
print (f"X: {x}, X shape: {x.shape}")
x_reshaped = x.reshape (1, 9)
print (f"X reshaped: {x_reshaped}, x_reshaped shape: {x_reshaped.shape}")

z = x.view (1, 9)
print (f"X view: {z}, z shape: {z.shape}")
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
print (f"z new: {z}, x new: {x}")

x_stacked = torch.stack ([x, x, x, x], dim=0)
print (f"X stacked: {x_stacked}")
print ()

# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor - squeeze: {x_squeezed}")
print(f"New shape - squeeze: {x_squeezed.shape}")
print ()

# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor - unsqueeze: {x_unsqueezed}")
print(f"New shape - unsqueeze: {x_unsqueezed.shape}")
print ()

# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand (size=(224, 224, 3)) 
x_permuted = x_original.permute (2, 0, 1)
print(f"Previous shape: {x_original.shape}") 
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

X: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), X shape: torch.Size([9])
X reshaped: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), x_reshaped shape: torch.Size([1, 9])
X view: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), z shape: torch.Size([1, 9])
z new: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), x new: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
X stacked: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor - squeeze: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape - squeeze: torch.Size([9])

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor - unsqueeze: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape - unsqueeze: torch.Size([1, 9])

Previous shape: torch.Size(

**k. Indexing**

In [62]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
print (f"x[0] = {x[0]}")
print (f"x[:,1] = {x[:,1]}")
print (f"x[1,2] = {x[1,2]}")
print (f"x[:2,:2] = {x[:2,:2]}")
print ("\nAdvanced Indexing:")
x = torch.arange(10, 20)
print (f"Choose list of elements: {x[[0,3,5]]}")
x = torch.arange (1, 10).view (3,3)
print (x)
rows = torch.tensor ([0,1,2])
cols = torch.tensor ([2,1,0])
print (f"x[rows, cols] = {x[rows, cols]}")

x[0] = tensor([10, 20, 30])
x[:,1] = tensor([20, 50, 80])
x[1,2] = 60
x[:2,:2] = tensor([[10, 20],
        [40, 50]])

Advanced Indexing:
Choose list of elements: tensor([10, 13, 15])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x[rows, cols] = tensor([3, 5, 7])


**l. PyTorch tensors & Numpy**

In [68]:
# Numpy --> PyTorch
array = np.arange (1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
print (f"Numpy: {array}")
print (f"PyTorch: {tensor}")
print ()

# PyTorch --> Numpy
tensor = torch.ones (7)
numpy_tensor = tensor.numpy ()
print (f"PyTorch: {tensor}")
print (f"Numpy: {numpy_tensor}")

Numpy: [1. 2. 3. 4. 5. 6. 7.]
PyTorch: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

PyTorch: tensor([1., 1., 1., 1., 1., 1., 1.])
Numpy: [1. 1. 1. 1. 1. 1. 1.]


**m. GPU - CPU - MPS**

In [73]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
device

device(type='mps')

In [71]:
torch.cuda.is_available()

False

In [ ]:
tensor = torch.tensor ([1,2,3])
print (tensor, tensor.device)
tensor_on_mps = tensor.to (device)
print (tensor_on_mps)

# Note: If tensor is on MPS/GPU, can't transform it to Numpt
print (tensor_on_mps.numpy ())

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='mps:0')


TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.